name: example-ngrok-kubesphere-v2
on:
  workflow_dispatch:

jobs:
  example-ngrok-kubesphere-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Creating kind cluster
        uses: helm/kind-action@v1.2.0
      - name: Install KubeSphere
        run: |
          kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.1.1/kubesphere-installer.yaml
          kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.1.1/cluster-configuration.yaml
      - name: Expose Port for Kind
        run: |
          export ID=`docker ps | awk '{print $1}' | sed -n '2p'`
          export IP=`docker inspect ${ID} |grep IPAddress | sed -n '2p'| grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'`
          sudo apt-get install socat
          socat TCP4-LISTEN:30880,reuseaddr,fork TCP4:${IP}:30880 &
      - uses: shaowenchen/debugger-action@v2
        name: debugger
        timeout-minutes: 300
        continue-on-error: true
        with:
          ngrok_token: ${{ secrets.NGROK_TOKEN }}
          ngrok_addr_1: 30880
          ngrok_proto_1: http